ION_RPC_ENDPOINT = 'https://api.mainnet.ice.io/http/v2/jsonRPC'

ION_RPC_API_KEY = ''

ION_DNS_COLLECTION_ADDRESS = 'EQDzBXQipGwp22WbLEA75bPW1fhHRLA7gMW0adlVnUgRqQqW'

ION_EXPLORER_ENDPOINT = 'https://explorer.ice.io'

MS_IN_ONE_LEAP_YEAR = 31622400000
SEC_IN_ONE_MONTH = 2592000
